version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      DATABASE_URL: postgres://user:password@db:5432/oscargdi
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: oscargdi
      POSTGRES_PASSWORD: password
volumes:
  postgres-data:
