version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      DATABASE_URL: postgres://user:password@db:5432/oscargdi
      AWS_ENDPOINT_URL: http://@localstack:4566
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: oscargdi
      POSTGRES_PASSWORD: password
  localstack:
    image: localstack/localstack:2.3.2
    environment:
      SERVICES: sqs
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  postgres-data:
